#!/usr/bin/env bun
// Reads ../design/tokens.json (W3C DTCG) and emits tokens.css.
// Idempotent: re-running produces byte-identical output. Mirrors the canonical
// loader at ../design/build-tokens.mjs; differs only in source and output paths.
//
// Mode-aware tokens: a leaf $value may be either a literal string (mode-agnostic)
// or an object { light, dark } (mode-aware). When mode-aware, we emit the light
// value in :root, then emit the dark value in two override blocks:
//   @media (prefers-color-scheme: dark) :root:not([data-theme]) { ... }
//   :root[data-theme="dark"] { ... }
// The OS-default block is scoped to :root:not([data-theme]) so a manual override
// always wins over the system preference. Single-value tokens emit once in :root.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_JSON = resolve(__dirname, "../design/tokens.json");
const OUT_CSS = resolve(__dirname, "tokens.css");

const tokens = JSON.parse(readFileSync(TOKENS_JSON, "utf8"));

const SKIP_PATHS = new Set([
  "typography.rule",
  "icons",
  "density",
]);

const FAMILY_TYPES = new Set(["fontFamily"]);

function kebab(s) {
  return String(s).replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function pathToVar(parts) {
  return "--" + parts.map(kebab).join("-");
}

function isLeaf(node) {
  return node && typeof node === "object" && "$value" in node && "$type" in node;
}

function isModeKeyed(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const keys = Object.keys(value);
  return keys.length === 2 && keys.includes("light") && keys.includes("dark");
}

function resolveRef(ref, root, mode) {
  if (typeof ref !== "string") return ref;
  const m = ref.match(/^\{([^}]+)\}$/);
  if (!m) return ref;
  const parts = m[1].split(".");
  let node = root;
  for (const p of parts) {
    if (node && typeof node === "object" && p in node) node = node[p];
    else return ref;
  }
  if (!isLeaf(node)) return ref;
  let v = node.$value;
  if (isModeKeyed(v)) v = v[mode];
  if (typeof v === "string") return resolveRef(v, root, mode);
  return v;
}

function formatShadow(value, root, mode) {
  if (value === "none" || value === null) return "none";
  if (typeof value !== "object") return String(value);
  let color = value.color;
  if (isModeKeyed(color)) color = color[mode];
  if (typeof color === "string") color = resolveRef(color, root, mode);
  return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${color}`;
}

function formatValue(node, root, mode) {
  const { $type: type } = node;
  let value = node.$value;
  if (type === "shadow") return formatShadow(value, root, mode);
  if (isModeKeyed(value)) value = value[mode];
  if (typeof value === "string") value = resolveRef(value, root, mode);
  if (FAMILY_TYPES.has(type)) {
    const v = String(value);
    return /\s/.test(v) ? `"${v}"` : v;
  }
  return String(value);
}

const GROUP_ORDER = [
  "color",
  "typography",
  "spacing",
  "grid",
  "radius",
  "depth",
  "motion",
  "breakpoint",
];

function walk(node, parts, out, root) {
  if (!node || typeof node !== "object") return;
  const pathStr = parts.join(".");
  if (SKIP_PATHS.has(pathStr)) return;
  if (isLeaf(node)) {
    if (Array.isArray(node.$value)) return;
    out.push({
      name: pathToVar(parts),
      light: formatValue(node, root, "light"),
      dark: formatValue(node, root, "dark"),
    });
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    walk(child, [...parts, key], out, root);
  }
}

const groupedTokens = [];
for (const group of GROUP_ORDER) {
  const node = tokens[group];
  if (!node) continue;
  const out = [];
  walk(node, [group], out, tokens);
  if (out.length > 0) groupedTokens.push({ group, tokens: out });
}

const lines = [];
lines.push("/* GENERATED by build-tokens.mjs from ../design/tokens.json. Do not edit. */");
lines.push("");
lines.push("/* Light defaults. Mode-aware tokens emit their light value here. */");
lines.push(":root {");
for (let i = 0; i < groupedTokens.length; i++) {
  const { group, tokens: items } = groupedTokens[i];
  if (i > 0) lines.push("");
  lines.push(`  /* ${group} */`);
  for (const { name, light } of items) {
    lines.push(`  ${name}: ${light};`);
  }
}
lines.push("}");

const darkGroups = [];
for (const { group, tokens: items } of groupedTokens) {
  const diff = items.filter((t) => t.light !== t.dark);
  if (diff.length > 0) darkGroups.push({ group, tokens: diff });
}

if (darkGroups.length > 0) {
  lines.push("");
  lines.push("/* Dark overrides. Applied when the OS prefers dark and the user has not set a manual override, plus when data-theme=\"dark\" is set explicitly. */");
  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push("  :root:not([data-theme]) {");
  for (let i = 0; i < darkGroups.length; i++) {
    const { group, tokens: items } = darkGroups[i];
    if (i > 0) lines.push("");
    lines.push(`    /* ${group} */`);
    for (const { name, dark } of items) {
      lines.push(`    ${name}: ${dark};`);
    }
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push(":root[data-theme=\"dark\"] {");
  for (let i = 0; i < darkGroups.length; i++) {
    const { group, tokens: items } = darkGroups[i];
    if (i > 0) lines.push("");
    lines.push(`  /* ${group} */`);
    for (const { name, dark } of items) {
      lines.push(`  ${name}: ${dark};`);
    }
  }
  lines.push("}");
}

lines.push("");

writeFileSync(OUT_CSS, lines.join("\n"));
console.log(`wrote ${OUT_CSS} (${lines.length} lines)`);
