#!/usr/bin/env bun
// Reads ../design/tokens.json (W3C DTCG) and emits tokens.css.
// Idempotent: re-running produces byte-identical output.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_JSON = resolve(__dirname, "../design/tokens.json");
const OUT_CSS = resolve(__dirname, "tokens.css");

const tokens = JSON.parse(readFileSync(TOKENS_JSON, "utf8"));

const SKIP_PATHS = new Set([
  "typography.rule",
  "icons",
  "density",
]);

const FAMILY_TYPES = new Set(["fontFamily"]);

function kebab(s) {
  return String(s).replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function pathToVar(parts) {
  return "--" + parts.map(kebab).join("-");
}

function isLeaf(node) {
  return node && typeof node === "object" && "$value" in node && "$type" in node;
}

// Resolve token references like "{color.shadow.warm}" against the full tree.
function resolveRef(ref, root) {
  const m = String(ref).match(/^\{([^}]+)\}$/);
  if (!m) return ref;
  const parts = m[1].split(".");
  let node = root;
  for (const p of parts) {
    if (node && typeof node === "object" && p in node) node = node[p];
    else return ref;
  }
  return isLeaf(node) ? node.$value : ref;
}

function formatShadow(value, root) {
  if (value === "none" || value === null) return "none";
  if (typeof value !== "object") return String(value);
  const color = resolveRef(value.color, root);
  return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${color}`;
}

function formatValue(node, root) {
  const { $type: type, $value: value } = node;
  if (type === "shadow") return formatShadow(value, root);
  if (FAMILY_TYPES.has(type)) {
    // Quote families that contain spaces; bare otherwise
    const v = String(value);
    return /\s/.test(v) ? `"${v}"` : v;
  }
  // dimension, duration, color, cubicBezier, number, string -> emit as-is
  return String(value);
}

// Group output for readability. Top-level keys we want grouped:
const GROUP_ORDER = [
  "color",
  "typography",
  "spacing",
  "grid",
  "radius",
  "depth",
  "motion",
  "breakpoint",
];

function walk(node, parts, out) {
  if (!node || typeof node !== "object") return;
  // Skip authoring-only branches
  const pathStr = parts.join(".");
  if (SKIP_PATHS.has(pathStr)) return;
  if (isLeaf(node)) {
    if (Array.isArray(node.$value)) return; // skip array tokens (e.g. customSvgPlacement)
    out.push([pathToVar(parts), formatValue(node, tokens)]);
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    walk(child, [...parts, key], out);
  }
}

const lines = [];
lines.push("/* GENERATED by build-tokens.mjs from ../design/tokens.json. Do not edit. */");
lines.push(":root {");

for (const group of GROUP_ORDER) {
  const node = tokens[group];
  if (!node) continue;
  const out = [];
  walk(node, [group], out);
  if (out.length === 0) continue;
  lines.push(`  /* ${group} */`);
  for (const [name, value] of out) {
    lines.push(`  ${name}: ${value};`);
  }
  lines.push("");
}

// Trim trailing blank line before closing brace
while (lines.length && lines[lines.length - 1] === "") lines.pop();
lines.push("}");
lines.push("");

writeFileSync(OUT_CSS, lines.join("\n"));
console.log(`wrote ${OUT_CSS} (${lines.length} lines)`);
